#spring配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
management:
  #配置了上下文路径需要在状态页面和健康检查前自动拼上路径
  server:
    servlet:
      context-path: /
  #刷新配置
  endpoints:
    web:
      exposure:
        include: bus-refresh

#注册中心配置
eureka:
  #实例配置
  instance:
    #ip注册
    preferIpAddress: true
    #注册名
    instance-id: ${spring.application.name}:123
    #租期更新时间间隔(默认30秒)
    lease-renewal-interval-in-seconds: 10
    #租期到期时间(默认90秒）
    lease-expiration-duration-in-seconds: 30

#feign
feign:
  hystrix:
    #启动断路器
    enabled: true

#断路器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          #修改断路器模式，防止请求头丢失
          strategy: SEMAPHORE
